### ISSUE TITLE
No module named 'edgetpu' on Coral Dev Board 

### ISSUE THREAD

**Issue by iverona** [google-coral/project-teachable#20]
I'm trying to run on a Coral Dev Board and I get:

```
$ sh run.sh
Traceback (most recent call last):
  File "teachable.py", line 28, in <module>
    from embedding import KNNEmbeddingEngine
  File "/home/mendel/project-teachable/embedding.py", line 18, in <module>
    from edgetpu.basic.basic_engine import BasicEngine
ModuleNotFoundError: No module named 'edgetpu'
```

Am I missing something? Shouldn't all the libraries be already installed, as the documentation states? `edgetpu_demo` runs ok. 

Thanks!

**Comment by hjonnala** [comment]
Hello @iverona this project needs to be updated with [pycoral API](https://github.com/google-coral/pycoral) as [edgeTPU API](https://github.com/google-coral/edgetpu) is deprecated. Unfortunately, we don't have any planned updates for this project.

**Comment by svndin** [comment]
Hey, I have the same problem and tried it with pycoral, but it does not work. Also I tried with python venv 3.7, unfortunately that doesn't work either.
I think some libraries no longer exist.
